BUCKET_NAME="image-processed"
REGION_NAME="us-east-2"
OUTPUT_BUCKET_DIR="output"
IMAGES_BUCKET_DIR="images"
SLASH="/"
JPG=".jpg"
ONE_HOUR_SECONDS=3600

SUCCESS_STATUS_CODE=200
CREATED_STATUS_CODE=202

NOT_ACCEPTABLE_STATUS_CODE={
  "status":406,
  "message":"NOT_ACCEPTABLE"
}
INTERNAL_SERVER_ERROR_STATUS_CODE={
  "status":500,
  "message":"INTERNAL_SERVER_ERROR"
}
